/**
 * SwingEdge Data Loader
 * Reads data.json (generated by scanner.py) and feeds it to the dashboard.
 * Falls back to demo data if data.json is not yet available.
 *
 * Include this BEFORE the main dashboard script:
 *   <script src="data_loader.js"></script>
 */

const DataLoader = {

  async load() {
    try {
      const res = await fetch('./data.json?v=' + Date.now());
      if (!res.ok) throw new Error('data.json not found');
      const data = await res.json();
      console.log(`✅ SwingEdge: Loaded real scan data — ${data.meta.date}`);
      console.log(`   Stocks qualified: ${data.meta.stocks_qualified}`);
      console.log(`   Macro signal: ${data.macro.signal}`);
      return data;
    } catch (e) {
      console.warn('⚠️  SwingEdge: data.json not found — using demo data');
      console.warn('   Run scanner.py to generate real data');
      return null;
    }
  },

  // Convert scanner output format to dashboard format
  mapStock(s) {
    return {
      id:           s.id,
      name:         s.name,
      sector:       s.sector,
      cap:          s.cap,
      price:        s.price,
      chg:          s.chg,
      pct:          s.pct,
      up:           s.up,
      style:        s.style,
      setup:        s.setup || 'Scan',
      themes:       s.themes || [],
      score:        s.score,
      swingScore:   s.swing_score,
      posScore:     s.pos_score,
      tech:         s.tech,
      fund:         s.fund,
      mom:          s.mom,
      theme:        s.theme,
      signal:       s.signal,
      signal_class: s.signal_class,
      entry:        s.entry,
      t1:           s.target_1,
      t2:           s.target_2,
      sl:           s.stop_loss,
      rr:           s.rr,
      hold:         s.hold,
      t1pct:        s.t1_pct,
      t2pct:        s.t2_pct,
      slpct:        s.sl_pct,
      rsi:          s.rsi,
      macd:         s.macd_signal,
      adx:          s.adx,
      supertrend:   s.supertrend,
      templatePass: s.template_passes,
      roe:          s.roe,
      roce:         s.roe,  // approximation until Stage 4 adds real ROCE
      de:           s.debt_equity,
      promo:        s.promoter,
      patGrowth:    s.earn_growth,
      revGrowth:    s.rev_growth,
      thesis:       `${s.name} showing ${s.setup} setup in ${s.sector} sector. RS vs Nifty: ${s.rs_vs_nifty > 0 ? '+' : ''}${s.rs_vs_nifty}% over 3 months. Template: ${s.template_passes}/8.`,
      thesisBroken: `Stock closes below ₹${s.stop_loss} (stop loss).`,
      catalysts:    [],
      risks:        [],
    };
  },

  mapMacro(macro) {
    return {
      score:       macro.macro_score,
      regime:      macro.regime,
      signal:      macro.signal,
      signalText:  macro.signal_text,
      riskAdvice:  macro.risk_advice,
      vix:         macro.india_vix,
      fii10d:      macro.fii_10day_cr,
      dii10d:      macro.dii_10day_cr,
      repoRate:    macro.rbi_repo_rate,
      cpi:         macro.cpi,
      gdp:         macro.gdp_growth,
      usdinr:      macro.usdinr,
      crude:       macro.brent_crude,
      niftyVs200:  macro.nifty_vs_200sma,
    };
  }
};

// Auto-load on page start
window.SWINGLEDGE_DATA_PROMISE = DataLoader.load();
